# Generated by Django 4.1.7 on 2023-03-31 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='dados',
            new_name='nome',
        ),
    ]
