# Generated by Django 4.1.7 on 2023-04-19 18:44

from django.db import migrations, models
import meuapp01.models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp01', '0002_rename_dados_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=meuapp01.models.upload_image_cad),
        ),
    ]
